-- Fix parts table identity sequence
-- This resets the sequence to the maximum ID value + 1
-- Run this if the parts.id sequence is out of sync

-- Method 1: For identity columns (GENERATED BY DEFAULT AS IDENTITY)
-- Find and reset the sequence associated with the identity column
DO $$
DECLARE
    max_id INTEGER;
    seq_name TEXT;
BEGIN
    -- Get the maximum ID value from the parts table
    SELECT COALESCE(MAX(id), 0) INTO max_id FROM parts;
    
    -- Find the sequence name for the identity column
    SELECT pg_get_serial_sequence('parts', 'id') INTO seq_name;
    
    IF seq_name IS NOT NULL THEN
        -- Reset the sequence to max_id + 1
        EXECUTE format('SELECT setval(%L, %s, false)', seq_name, max_id + 1);
        RAISE NOTICE 'Sequence % reset to %', seq_name, max_id + 1;
    ELSE
        RAISE NOTICE 'No sequence found for parts.id - it may not be an identity column';
    END IF;
END $$;

-- Method 2: Direct approach (if you know the sequence name)
-- Uncomment and use if Method 1 doesn't work:
-- SELECT setval('parts_id_seq', COALESCE((SELECT MAX(id) FROM parts), 0) + 1, false);

-- Method 3: Alternative using ALTER SEQUENCE (if sequence name is known)
-- ALTER SEQUENCE parts_id_seq RESTART WITH (SELECT COALESCE(MAX(id), 0) + 1 FROM parts);

